service: batch-submit

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  timeout: 60

functions:
  ingcomSubmit:
    handler: handler.ingcom_submit
    layers:
        - arn:aws:lambda:eu-central-1:189416701607:layer:ingcom_lambda_layer:2        
package:
    individually: true
    exclude:
        - "input.json"
        - "*.env"
        - ".env"
        - "Pipfile"
        - "Pipfile.*"
        - ".python-version"
        - ".gitignore"
        - "*__pycache__/***"
        - "*.git/***"

