service: batch-submit

provider:
  name: aws
  runtime: python3.7
  role: arn:aws:iam::189416701607:role/service-role/lambdaBatchRole
  region: eu-central-1
  timeout: 60

functions:
  ingcomSubmit:
    handler: handler.ingcom_submit
    layers:
        - arn:aws:lambda:eu-central-1:189416701607:layer:ingcom_lambda_layer        
package:
    individually: true
    exclude:
        - "input.json"
        - "*.env"
        - ".env"
        - "Pipfile"
        - "Pipfile.*"
        - ".python-version"
        - ".gitignore"